set nocompatible

" Pathogen
call pathogen#infect()
filetype plugin indent on

" Behaviors
set title
set shortmess+=I
set hidden
set noswapfile
set backspace=indent,eol,start
set mouse=a
set scrolloff=3
set nowrap
set autowrite
set linebreak
set listchars=tab:▸\ ,eol:¬,trail:·

" Hotkeys
inoremap <C-c> <Esc>
let g:ctrlp_map = "<leader>t"
let mapleader=","
nnoremap ; :
nmap <silent> <leader>rc :e $MYVIMRC<CR>
nmap <silent> <leader>/ :nohlsearch<CR>
nmap <silent> <leader>l :set list!<CR>
" Run current script
nmap <F5> :!echo -ne "\ec\e[3J" ; %:p<CR>

" Indent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent

" Statusbar
set showmode
set showcmd
set ruler

" Colors
set background=dark
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

" TRASH
set incsearch
syntax on
set nowrap
set number
set numberwidth=4

if has("autocmd")
	autocmd! BufWritePost .vimrc 
	autocmd BufWritePost .vimrc source $MYVIMRC
endif
