set nocompatible

" Pathogen
call pathogen#infect('~/.vim/bundle/snipmate')
call pathogen#infect()
filetype plugin indent on

" Behaviors
set title
set shortmess+=I
set hidden
set noswapfile
set backspace=indent,eol,start
set mouse=a
set scrolloff=0
set nowrap
set autowrite
set linebreak
set ignorecase
set smartcase
set listchars=tab:▸\ ,eol:¬,trail:·
set fillchars=vert:│
set noshowmode
set laststatus=2
let NERDTreeMinimalUI=1

"nmap y "+y
"vmap y "+y
"nmap p "+p
"vmap p "+p
"nmap P "+P
"nmap D "+D
"nmap d "+d
"vmap d "+d

" Hotkeys
inoremap jj <Esc>
inoremap <C-c> <Esc>
inoremap <C-c> <Esc>
let mapleader=","
nnoremap ; :
nmap <silent> <leader>rc :e $MYVIMRC<CR>
nmap <silent> <leader>/ :set hlsearch!<CR>
nmap <silent> <leader>l :set list!<CR>
nmap <silent> <leader>t :NERDTreeToggle<CR>
nmap <silent> <leader>n :NERDTreeFind<CR>
" Run current script
nmap <F5> :!echo -ne "\ec\e[3J" ; %:p<CR>
nnoremap <Leader>s :%s/\<<C-r><C-w>\>//g<Left><Left>

" Indent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent

" Statusbar
let g:Powerline_symbols="fancy"
set showcmd
set noruler

" Colors
set background=dark
let g:solarized_termcolors = 256
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"
colorscheme solarized

" TRASH
set incsearch
syntax on
set nowrap
set number
set numberwidth=4

" Auto source .vimrc
if has("autocmd")
	autocmd! BufWritePost .vimrc 
	autocmd BufWritePost .vimrc source $MYVIMRC
endif

"
" ActionScriptCompiler
"
compiler mxmlc
nmap <C-B> :make<CR>
nmap <C-N> :!adl.exe descriptor.xml -screensize iPhone<CR>
set wildignore=*.swc,*.swf,ctags,*.apk
